"use client";

import { WalletCheckResponse, formatUSDFull, truncateAddress, RiskLevel, RISK_CONFIG } from "@/lib/metacomp";
import { FileText, Calendar, Shield } from "lucide-react";
import { cn } from "@/lib/utils";

interface ComplianceReportProps {
  data: WalletCheckResponse["data"];
}

export function ComplianceReport({ data }: ComplianceReportProps) {
  const config = RISK_CONFIG[data.level];

  return (
    <div className="bg-slate-800/50 border border-slate-700/50 rounded-xl p-5">
      <div className="flex items-center gap-2 mb-4">
        <FileText className="h-4 w-4 text-slate-400" />
        <h3 className="text-sm font-semibold text-slate-300">Compliance Report</h3>
      </div>

      <div className="space-y-3 text-xs">
        <Row label="Wallet Address" value={truncateAddress(data.address, 10)} mono />
        <Row label="Network" value={data.network} />
        <Row label="Risk Level">
          <span className={cn("font-bold", config.text)}>{data.level}</span>
        </Row>
        <Row label="Screening Date" value={new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} />
        <Separator />
        <Row label="Total Incoming" value={formatUSDFull(data.extra.totalIncoming)} mono />
        <Row label="Total Outgoing" value={formatUSDFull(data.extra.totalOutgoing)} mono />
        <Row label="Wallet Balance" value={formatUSDFull(data.extra.walletBalance)} mono />
        <Separator />
        <Row label="High-Risk Categories" value={data.extra.highRiskCategories.length.toString()} />
        {data.extra.highRiskCategories.length > 0 && (
          <div className="flex flex-wrap gap-1.5 ml-24 mt-1">
            {data.extra.highRiskCategories.map((cat, idx) => (
              <span
                key={idx}
                className="px-2 py-0.5 rounded-full text-[10px] bg-red-500/10 border border-red-500/20 text-red-400"
              >
                {cat}
              </span>
            ))}
          </div>
        )}
        <Separator />
        <Row label="Incoming High-Risk" value={formatUSDFull(data.extra.incomingRiskExposureBreakdown.highRiskAmount)} mono />
        <Row label="Outgoing High-Risk" value={formatUSDFull(data.extra.outgoingRiskExposureBreakdown.highRiskAmount)} mono />
      </div>

      <div className="mt-4 pt-4 border-t border-slate-700/30 flex items-center gap-2 text-[10px] text-slate-600">
        <Shield className="h-3 w-3" />
        Generated by MetaComp Vision X — Multi-Vendor AML Screening
      </div>
    </div>
  );
}

function Row({
  label,
  value,
  mono,
  children,
}: {
  label: string;
  value?: string;
  mono?: boolean;
  children?: React.ReactNode;
}) {
  return (
    <div className="flex items-start gap-3">
      <span className="text-slate-500 w-36 shrink-0">{label}</span>
      {children || (
        <span className={cn("text-slate-300", mono && "font-mono")}>{value}</span>
      )}
    </div>
  );
}

function Separator() {
  return <div className="border-t border-slate-700/20 my-2" />;
}
